language: node_js

node_js:
  - "lts/*"

cache:
  yarn: true
  directories:
    - node_module

script:
  - yarn type-check
  - yarn lint
  - yarn test:cov

notifications:
  email:
    on_failure: change

after_success:
  - yarn coveralls

before_deploy:
  - yarn build:demo

deploy:
  provider: netlify
  site: $NETLIFY_SITE_ID
  auth: $NETLIFY_ACCESS_TOKEN
  edge: true # opt in to dpl v2
  on:
    branch: master

