language: node_js

node_js:
  - "lts/*"

notifications:
  email:
    on_failure: change

cache:
  yarn: true
  directories:
    - node_module

script:
  - yarn type-check
  - yarn lint
  - yarn test:cov

before_deploy:
  - yarn global add netlify-cli
  - yarn build:demo

deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p ./demo
  skip_cleanup: true
  on:
    branch: master

after_success:
  - yarn coveralls
